language: go

sudo: false

go:
  - 1.6
  - 1.7
  - tip
  
install:
  - go get github.com/Masterminds/glide
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - cd src && $GOPATH/bin/glide install
  - go test $($GOPATH/bin/glide novendor)  
  - $GOPATH/bin/overalls -project=github.com/jasonlam604/yahoofinance -covermode=count -ignore=.git,vendor -debug

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
